models:
  - type: main
    engine: openai  # Placeholder, overridden in Python
    model: llama3-70b-8192
    parameters:
      temperature: 0.7
      max_tokens: 350

rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check output

colang_version: "1.0"
