models:
  - type: main
    engine: langchain
    model: llama3-70b-8192
    parameters:
      temperature: 0.7
      max_tokens: 350

rails:
  input:
    flows:
      - check_toxicity
      - check_politics
      - check_illegal
  output:
    flows:
      - limit_response_length
      - enforce_citations

colang_version: "1.0"
